version: '3.8'

services:
  bot:
    build: .
    container_name: arb-bot-dev
    restart: always
    environment:
      - APP_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "src/main.py"]
