FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    libatlas-base-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8501
CMD bash -lc "\
  python -m src.init_db && \
  python -m src.notify && \
  python -m src.main & \
  streamlit run dashboard.py --server.port 8501 --server.headless true"
