version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: arbbot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SQLITE_DB_PATH=${SQLITE_DB_PATH}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_SECRET=${BYBIT_SECRET}
      - PAIR=${PAIR}
      - SPREAD_THRESHOLD=${SPREAD_THRESHOLD}
      - TRADE_SIZE=${TRADE_SIZE}
      - DESIRED_NOTIONAL_USD=${DESIRED_NOTIONAL_USD}
      - DRY_RUN=${DRY_RUN}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}

volumes:
  db_data: