name: Phase 2 CI Build

on:
  push:
    branches:
      - feature/**
      - development
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and format check
        run: |
          pip install flake8
          flake8 src/ tests/

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

  deploy-test:
    if: github.ref == 'refs/heads/test'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pre-production
        run: echo "Deploying to Lightsail (test environment)"

  deploy-prod:
    if: github.ref == 'refs/heads/production'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to Lightsail (production environment)"
